# Site data
title: "EVs Calculator API"
email: social@evscalculator.com
description: "API documentation for EVs Calculator project."
baseurl: ""
url: "https://docs.evscalculator.com"
enforce_ssl: "http://docs.evscalculator.com"
username: "evscalculator"

api_url: https://api.evscalculator.com


collections: 
 - projects
 - work

 # Default front-matter
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: default
  -
    scope:
      path: ""
    values: 
      image: "/apple-touch-icon.png"



# Build settings
permalink: pretty
exclude:
  - README.md
  - _src/
  - node_modules/
  - Gruntfile.js
  - package.json
  - api

#Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed